[v7r1] [WIP] Allow to transfer from tape using different staging and transfer protocols (CTA)
DIRACGrid/DIRAC pull request #4891
Opened 2021-01-12 14:53 UTC by chaen

Up to now, when copying files from a tape system, you would always use `SRM` for everything: staging and copying. This is not true anymore with CTA that can only stage via xroot but transfer with more protocols.

This PR implements the split between the transfer/access protocols and the staging protocols, as well as the necessary machinery to perform the protocol translation with FTS. 
It should be totally transparent to existing configuration, and really only useful for CTA (today at least)
I won't comment much more, because more info are in the PR's doc

This PR is awaiting for 2 fixes on the FTS side as well as configuration changes on the CTA side to be completely tested.

**IMPORTANT** it will require a simple db update that I will add to the wiki

BEGINRELEASENOTES

*DMS
CHANGE: split staging and access protocols
NEW: FTS3 can submit transfers with staging protocols different from transfer protocols

ENDRELEASENOTES

2021-01-14 15:16 UTC, fstagni commented
Just somewhat related, FYI: https://indico.cern.ch/event/876772/contributions/4175665/attachments/2170369/3664231/REST%20for%20Tape.pdf

2021-01-14 15:56 UTC, chaen commented
Yep exactly. That's what the `(today at least)` comment in the PR description refers to :-) And this time, they seem to have realistic objectives (at least they had. Then some people started having ideas to make it another monster....) so I have good hope it will be in a reasonable timescale :-)

2021-01-29 09:59 UTC, chaen commented
@andresailer you can start reviewing. I am still doing final tests, but I think it is pretty much final version

2021-02-02 14:59 UTC, fstagni commented on Resources/Storage/StorageElement.py
> +        :return: dictionnary with keys::
```suggestion
        :return: dictionary with keys::
```
:)

2021-02-02 17:28 UTC, chaen commented on Resources/Storage/StorageElement.py
> +        :return: dictionnary with keys::
:-D The usual :-)

2021-02-03 10:17 UTC, fstagni commented
@andresailer  the final review of this is for you!

2021-02-03 12:28 UTC, atsareg commented on DataManagementSystem/Client/FTS3Job.py
> +      # * stageProto://myFile -> stageProto://myFile
Is it like that ?
```suggestion
      # * stageProto://myFile -> srcProto://myFile
```

2021-02-03 13:08 UTC, andresailer requested changes
There are couple small things that need to be fixed.

2021-02-03 13:08 UTC, andresailer commented on DataManagementSystem/Client/FTS3Job.py
> +      if srcProto not in srcSE.localStageProtocolList:
I asked @chaen directly what srcProto and localStageProtocolList is for CTA, because I got lost

2021-02-03 15:44 UTC, chaen commented on Resources/Storage/CTAStorage.py
> +              StageProtocols = root
to myself: add HTTPs config in the example

2021-02-03 15:49 UTC, chaen commented on docs/source/AdministratorGuide/Resources/storage.rst
> +Up to recently, any protocol that was defined as `AccessProtocol` was also used for staging (plot twister: only `srm` could do it).
Also double backtick

2021-02-03 16:25 UTC, chaen commented on DataManagementSystem/Client/FTS3Job.py
> +    # to do a multihop transfer. See bellow.
fixed

2021-02-03 16:26 UTC, chaen commented on DataManagementSystem/Client/FTS3Job.py
> +        for lfn, reason in res['Value']['Failed'].iteritems():
thanks, fixed

2021-02-03 16:27 UTC, chaen commented on DataManagementSystem/Client/FTS3Job.py
> +      trans_metadata = {'desc': 'Stage %s' % ftsFileID, 'fileID': ftsFileID}
You want it in the transfer or in the job, or in both ?

2021-02-03 16:28 UTC, chaen commented on DataManagementSystem/Client/FTS3Job.py
> +    # as filesize
yup

2021-02-03 16:28 UTC, chaen commented on DataManagementSystem/Client/FTS3Job.py
> +    # Same as above for the condition
done

2021-02-03 16:29 UTC, chaen commented on DataManagementSystem/Client/FTS3Operation.py
> +    srcSE = StorageElement(sourceSEName, vo=self._vo)
well spotted, fixing it

2021-02-03 16:31 UTC, chaen commented on Resources/Storage/StorageElement.py
> +        :return: dictionary with keys::
ok, done

2021-02-03 16:59 UTC, chaen commented on DataManagementSystem/Client/FTS3Job.py
> +      trans_metadata = {'desc': 'Stage %s' % ftsFileID, 'fileID': ftsFileID}
Added in the Job

2021-02-05 12:05 UTC, andresailer reviewed
Just some proposals for changes in the comments. What had me initially confused, was that I thought CTA always has stageprotocol != transferprotocol. That this is not the case is explained in the storage.rst, but some of the existing comments might make one think that, so I propose the modifications

2021-02-05 12:08 UTC, andresailer approved these changes

2021-02-05 13:38 UTC, chaen commented
@andresailer  Thanks for the improvements, I committed them, please reaprove

2021-02-05 13:52 UTC, andresailer commented on Resources/Storage/CTAStorage.py
> +              # This is very important if you have to stage with this protocol,  but might transfer
```suggestion
              # This is very important if you have to stage with this protocol,  but might transfer
```

2021-02-05 13:57 UTC, andresailer approved these changes

2021-02-05 15:19 UTC, chaen commented
@atsareg it would be great if you could quickly do a release with that one in, using DIRACOS 1.17 (the latest). I'd like to deploy it early next week. Thanks !

2021-02-08 10:23 UTC, merged