Modifications to manage certificates to access the Elias (Elaasticsea…
DIRACGrid/DIRAC pull request #4924
Opened 2021-01-26 14:39 UTC by sanguillon

BEGINRELEASENOTES

Configuration we used in /opt/dirac/etc/dirac.cfg to access the ELIAS database hosted at CC-IN2P3
-----------------------------
/DIRAC/Setups/CTA-cert/Monitoring = Certification

/Systems/Monitoring/Certification/Databases/MonitoringDB
          {
          Host = elias-beta.cc.in2p3.fr
          Port = 9200
          SSL = False
          IndexPrefix = cta-
          CRT = True
          ca_certs = /opt/dirac/etc/grid-security/ES/ca.crt
          client_key = /opt/dirac/etc/grid-security/ES/ctacertbot.key
          client_cert = /opt/dirac/etc/grid-security//ES/ctacertbot.crt
        }

ENDRELEASENOTES

2021-01-26 14:50 UTC, fstagni requested changes
Thanks!
It's missing some changes in the documentation too.

2021-01-26 14:50 UTC, fstagni commented on ConfigurationSystem/Client/Utilities.py
> +    # No host name found, try at the common place
Wrong (copy-pasted) comment (also below).

2021-01-26 14:50 UTC, fstagni commented on ConfigurationSystem/Client/Utilities.py
> +      gLogger.warn("Failed to get the configuration parameter: certs. Using False")
`certs` or `CRT` ?

2021-01-26 14:50 UTC, fstagni commented on Core/Utilities/ElasticSearchDB.py
> +                                  timeout=self.__timeout,
bad indentation.

2021-01-26 15:18 UTC, sanguillon commented
Hi Federico,

I am sorry for these errors that I fixed.
Could you please tell me the procedure I have to use to check/validate the code before submitting a pull request?
Thank you in advance for your answer.

Michele

> Le 26 janv. 2021 à 15:50, fstagni <notifications@github.com> a écrit :
> 
> 
> @fstagni requested changes on this pull request.
> 
> Thanks!
> It's missing some changes in the documentation too.
> 
> In ConfigurationSystem/Client/Utilities.py <https://github.com/DIRACGrid/DIRAC/pull/4924#discussion_r564567220>:
> 
> > @@ -530,6 +530,62 @@ def getElasticDBParameters(fullname):
>      ssl = False if result['Value'].lower() in ('false', 'no', 'n') else True
>    parameters['SSL'] = ssl
>  
> +  # Elasticsearch use certs
> +  result = gConfig.getOption(cs_path + '/CRT')
> +  if not result['OK']:
> +    # No host name found, try at the common place
> Wrong (copy-pasted) comment (also below).
> 
> In ConfigurationSystem/Client/Utilities.py <https://github.com/DIRACGrid/DIRAC/pull/4924#discussion_r564567439>:
> 
> > @@ -530,6 +530,62 @@ def getElasticDBParameters(fullname):
>      ssl = False if result['Value'].lower() in ('false', 'no', 'n') else True
>    parameters['SSL'] = ssl
>  
> +  # Elasticsearch use certs
> +  result = gConfig.getOption(cs_path + '/CRT')
> +  if not result['OK']:
> +    # No host name found, try at the common place
> +    result = gConfig.getOption('/Systems/NoSQLDatabases/CRT')
> +    if not result['OK']:
> +      gLogger.warn("Failed to get the configuration parameter: certs. Using False")
> certs or CRT ?
> 
> In Core/Utilities/ElasticSearchDB.py <https://github.com/DIRACGrid/DIRAC/pull/4924#discussion_r564569556>:
> 
> > @@ -105,6 +110,14 @@ def __init__(self, host, port, user=None, password=None, indexPrefix='', useSSL=
>                                    use_ssl=True,
>                                    verify_certs=True,
>                                    ca_certs=casFile)
> +    elif useCRT:
> +        self.client = Elasticsearch(self.__url,
> +                                  timeout=self.__timeout,
> bad indentation.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/DIRACGrid/DIRAC/pull/4924#pullrequestreview-576421437>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ABWD6GNJ7CEQSZOVPTGJB2TS33JE3ANCNFSM4WTR2K3A>.
>

2021-01-26 17:07 UTC, fstagni commented
No problem, we all commit/fix/re-fix PRs. There's quite some doc in https://dirac.readthedocs.io/en/integration/DeveloperGuide/index.html and for the tests we run a mix of unit and integration tests, as well as static code checks and so on. 
We also run "certification hackathons" every 2nd week on pre-releases.

2021-01-29 12:11 UTC, fstagni commented on ConfigurationSystem/Client/Utilities.py
> +    # No host name found, try at the common place
Just change this comment please, and the ones below, and then I approve.

2021-01-29 13:39 UTC, sanguillon commented
Done! Thank you!
Cheers,
Michèle

> Le 29 janv. 2021 à 13:11, fstagni <notifications@github.com> a écrit :
> 
> 
> @fstagni commented on this pull request.
> 
> In ConfigurationSystem/Client/Utilities.py <https://github.com/DIRACGrid/DIRAC/pull/4924#discussion_r566779457>:
> 
> > @@ -530,6 +530,62 @@ def getElasticDBParameters(fullname):
>      ssl = False if result['Value'].lower() in ('false', 'no', 'n') else True
>    parameters['SSL'] = ssl
>  
> +  # Elasticsearch use certs
> +  result = gConfig.getOption(cs_path + '/CRT')
> +  if not result['OK']:
> +    # No host name found, try at the common place
> Just change this comment please, and the ones below, and then I approve.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/DIRACGrid/DIRAC/pull/4924#discussion_r566779457>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ABWD6GJZG2IUSP6EZ3S6KRDS4KQYHANCNFSM4WTR2K3A>.
>

2021-01-29 14:07 UTC, fstagni approved these changes

2021-02-03 12:37 UTC, merged