[v6r22] MySQL LIKE Query
DIRACGrid/DIRAC pull request #4927
Opened 2021-01-28 06:52 UTC by dhrjklt

BEGINRELEASENOTES
Ability to perform LIKE queries using DIRAC native MySQL API. 

*Core
CHANGE: Adding MySQL LIKE query feature.

ENDRELEASENOTES

2021-01-28 14:13 UTC, fstagni submitted a review, later dismissed

2021-02-01 07:56 UTC, chaen commented
What's the use case exactly ? Somehow, this makes me feel unsafe  from the injection POV. Rather than parsing with regex, I'd add an extra parameter to the call, explicitly for parameters requiring a `LIKE` statement. This would also limit the places where *mistakes* can happen and DDOS the DB...

2021-02-01 09:15 UTC, chrisburr requested changes
I agree with Chris. I'm fairly sure this would cause LFNs like `/lhcb/user/c/cburr/2016_first_50%.root` to match lots of entries that aren't intended. The same would apply to job names, groups, minor/application status and probably more values.

2021-02-17 16:30 UTC, fstagni commented
Dear @dhrjklt would you please consider the comments above?

2021-02-18 04:14 UTC, dhrjklt commented
Dear @fstagni  sorry for the late reply. I'm working on it.

2021-02-19 07:46 UTC, chrisburr commented on Core/Utilities/MySQL.py
> +import re
I think this is no longer used:
```suggestion
```

2021-02-19 07:54 UTC, dhrjklt commented on Core/Utilities/MySQL.py
> +import re
sorry, fixed!

2021-02-19 08:04 UTC, hmiyake commented on Core/Utilities/MySQL.py
> +                     greater=None, smaller=None, offset=None, likeQuery=False):
You may add explanation of the switch in docstring

2021-02-24 07:32 UTC, dhrjklt commented
@fstagni and @chrisburr please let me know if the changes are okay?

2021-02-24 09:43 UTC, chaen commented
Seems ok to me

2021-02-24 09:58 UTC, chrisburr commented
Seem okay 👍

Minor comment: Perhaps `likeQuery` should be `useLikeQuery` to make it clear it's a boolean (naively reading the name I would expect it to be a string).

2021-02-24 11:29 UTC, fstagni approved these changes

2021-02-24 11:43 UTC, dhrjklt commented
@chrisburr fixed!

2021-02-24 15:21 UTC, atsareg commented
Is there a particular reason to make it against v6r22 branch ? Can it go to v7r1 instead ?

2021-02-25 05:39 UTC, fstagni commented
I think the reason is that this is requested by Belle2 who is still on v6r22. TBH I would bump it to at least v7r0.

2021-03-03 01:40 UTC, dhrjklt commented
Dear @atsareg  and @fstagni,

Sorry for my late reply. I just confirmed with Belle2 and they confirmed that they are leaving v6r22 and v7r0 is preferable.

2021-03-03 12:54 UTC, atsareg approved these changes

2021-03-03 12:54 UTC, merged