[v7r3] docs: added better docs for JobShare and priorities
DIRACGrid/DIRAC pull request #5928
Opened 2022-03-09 10:17 UTC by fstagni

BEGINRELEASENOTES

*docs
FIX: added better docs for JobShare and priorities

ENDRELEASENOTES

2022-03-09 15:04 UTC, atsareg commented on docs/source/AdministratorGuide/Systems/WorkloadManagement/JobPriorities/index.rst
> +Administrators can set a different job shares depending on the user's group that runs the jobs,
```suggestion
Administrators can set different job shares depending on the user's group that runs the jobs,
```

2022-03-09 15:05 UTC, atsareg approved these changes, later dismissed

2022-03-09 17:52 UTC, andresailer requested changes
Some table of content tree needs an update after the rename of the file.

And a couple of typos/grammar

```
/home/docs/checkouts/readthedocs.org/user_builds/dirac/checkouts/5928/docs/source/AdministratorGuide/Systems/WorkloadManagement/index.rst:80: WARNING: toctree contains reference to nonexisting document 'AdministratorGuide/Systems/WorkloadManagement/JobPriorities'
/home/docs/checkouts/readthedocs.org/user_builds/dirac/checkouts/5928/docs/source/DeveloperGuide/Internals/index.rst:5: WARNING: toctree contains reference to nonexisting document 'AdministratorGuide/Systems/WorkloadManagement/JobPriorities/index'
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/docs/checkouts/readthedocs.org/user_builds/dirac/checkouts/5928/docs/source/AdministratorGuide/Systems/WorkloadManagement/JobsPriorities.rst: WARNING: document isn't included in any toctree
```

2022-03-15 09:18 UTC, andresailer commented
Still one warning
```
/home/docs/checkouts/readthedocs.org/user_builds/dirac/checkouts/5928/docs/source/DeveloperGuide/Internals/index.rst:5: WARNING: toctree contains reference to nonexisting document 'AdministratorGuide/Systems/WorkloadManagement/JobPriorities/index'
```

2022-03-17 11:41 UTC, fstagni commented
I guess OK to merge now!

2022-03-17 11:41 UTC, merged