[8.0] fixes for sql alchemy2.0
DIRACGrid/DIRAC pull request #6739
Opened 2023-01-30 10:21 UTC by chaen

closes https://github.com/DIRACGrid/DIRAC/issues/6737

BEGINRELEASENOTES

*DMS
CHANGE: adapt FTS3DB to sqlalchemy 2.0

*RMS
CHANGE: adapt ReqDB to sqlalchemy 2.0

ENDRELEASENOTES

2023-01-30 10:26 UTC, chrisburr submitted a review, later dismissed

2023-01-30 10:27 UTC, andresailer requested changes
Also for 7.3 please!

2023-01-30 10:27 UTC, chrisburr commented
Actually this should target v7r3

2023-01-30 10:44 UTC, chaen commented
Grrrr I anyway have to make two PRs since `pyupgrade` makes conflict, so I will backport

2023-01-30 10:52 UTC, chrisburr commented
Looks like there is something else:

> getRequest: unexpected exception : Strings are not accepted for attribute names in loader options; please use class-bound attributes directly

2023-01-30 13:50 UTC, andresailer approved these changes, later dismissed
Documentation builds again :heavy_check_mark:

2023-01-31 08:49 UTC, chrisburr commented
@chaen Do you understand why pylint keeps timing out?

2023-01-31 10:26 UTC, chaen commented
I thought it was due to the problems github were having yesterday, but apparently not. I am investigating

2023-02-01 15:39 UTC, chrisburr commented on pyproject.toml
> + ignored-modules = ["MySQLdb", "numpy"]
```suggestion
ignored-modules = ["MySQLdb", "numpy"]
```

2023-02-01 15:51 UTC, chaen commented on pyproject.toml
> + ignored-modules = ["MySQLdb", "numpy"]
thanks

2023-02-01 16:07 UTC, fstagni commented on src/DIRAC/Core/Tornado/Server/private/BaseRequestHandler.py
> +from typing import cast
What's this for?

2023-02-01 16:07 UTC, fstagni commented on src/DIRAC/Core/Tornado/Server/private/BaseRequestHandler.py
> +        if not isinstance(cls.SUPPORTED_METHODS, tuple):
Correct the comment few lines above.

2023-02-01 16:07 UTC, fstagni commented on src/DIRAC/Core/Utilities/Pfn.py
> +            if "?" in pfnDict["WSUrl"] and "=" in pfnDict["WSUrl"]:  # pylint: disable = unsupported-membership-test
```suggestion
            if "?" in pfnDict["WSUrl"] and "=" in pfnDict["WSUrl"]:  # pylint: disable=unsupported-membership-test
```

2023-02-01 16:35 UTC, chaen commented on src/DIRAC/Core/Tornado/Server/private/BaseRequestHandler.py
> +from typing import cast
an attempt which failed. I'll remove

2023-02-01 20:44 UTC, fstagni approved these changes

2023-02-01 20:44 UTC, merged