[8.1] TS: username instead of DN
DIRACGrid/DIRAC pull request #7124
Opened 2023-07-26 09:06 UTC by fstagni

- [ ] add to wiki -- similar to TQDB

BEGINRELEASENOTES

*TransformationSystem
CHANGE: use userName instead of DN

ENDRELEASENOTES

2023-07-26 14:41 UTC, andresailer commented
For the update script for TQDB:

Is there an `f` missing for the query string?
```python
for ownerDN, owner in dnToOwner.items():
    query = "UPDATE `tq_TaskQueues` SET `Owner` = {owner} WHERE `OwnerDN` = {ownerDN}"
#          ^     
    res = tqDB._query(query)
    if not res["OK"]:
        print(f"ERROR -- {res['Message']}")
        exit(1)
````
https://github.com/DIRACGrid/DIRAC/wiki/DIRAC-8.1#remove-of-diracsetup-and-ownerdn

2023-07-26 14:49 UTC, andresailer requested changes
One f-string replacement isn't correct

2023-07-26 14:49 UTC, andresailer commented on src/DIRAC/TransformationSystem/DB/TransformationDB.py
> +        message = f"Deleted tasks from {taskIDbottom} to {taskIDtop}" % (taskIDbottom, taskIDtop)
```suggestion
        message = f"Deleted tasks from {taskIDbottom} to {taskIDtop}"
```

2023-07-26 15:22 UTC, fstagni commented
> For the update script for TQDB:
> 
> Is there an `f` missing for the query string?
> 
> ```python
> for ownerDN, owner in dnToOwner.items():
>     query = "UPDATE `tq_TaskQueues` SET `Owner` = {owner} WHERE `OwnerDN` = {ownerDN}"
> #          ^     
>     res = tqDB._query(query)
>     if not res["OK"]:
>         print(f"ERROR -- {res['Message']}")
>         exit(1)
> ```
> 
> https://github.com/DIRACGrid/DIRAC/wiki/DIRAC-8.1#remove-of-diracsetup-and-ownerdn

Thanks, fixed. A very similar script (or better a patch of this one) will be needed to update TransformationDB too.

2023-07-26 15:25 UTC, andresailer commented
> Thanks, fixed. A very similar script (or better a patch of this one) will be needed to update TransformationDB too.

Yeah, that's why I looked at the change notes.
My biggest question would be about what to do about DNs that are no longer registered, either because the user is no longer present, or they changed their DN for some reason

2023-07-26 15:32 UTC, fstagni commented
> > Thanks, fixed. A very similar script (or better a patch of this one) will be needed to update TransformationDB too.
> 
> My biggest question would be about what to do about DNs that are no longer registered, either because the user is no longer present, or they changed their DN for some reason

Ah, good one. Suggestions?

2023-07-26 17:52 UTC, andresailer commented
Either use a default username, or add a map of old DN to username, or just "inactive" or something? Those should be for no-longer active transformations anyway.

2023-07-28 09:10 UTC, fstagni commented
> Either use a default username, or add a map of old DN to username, or just "inactive" or something? Those should be for no-longer active transformations anyway.

I have updated the script. Please have a look at that, and review this PR too.

2023-07-28 09:23 UTC, andresailer commented
https://github.com/DIRACGrid/DIRAC/wiki/DIRAC-8.1#remove-of-diracsetup-and-ownerdn
```mysql
ALTER TABLE `Transformations` MODIFY COLUMN `AuthorDN` VARCHAR(255)ssssssssssssssssssssssssssssssssssssssssssssssss;
```
?

2023-07-28 09:59 UTC, fstagni commented
;-) fixed

2023-08-01 12:08 UTC, fstagni commented
@andresailer review OK now? I have addressed the requested changes.

2023-08-01 14:01 UTC, andresailer approved these changes

2023-08-02 08:29 UTC, merged