[sweep:integration] feat (TS): add getTransformationFilesAsJsonString
DIRACGrid/DIRAC pull request #7843
Opened 2024-10-17 11:40 UTC by DIRACGridBot

Sweep #7840 `feat (TS): add getTransformationFilesAsJsonString` to `integration`.

Adding original author @chaen as watcher.

BEGINRELEASENOTES

*Core
FIX: Returning DISET responses with >100000000 bytes

*Transformation
NEW: Use getTransformationFilesAsJsonString for faster getTransformationFiles

ENDRELEASENOTES

2024-10-17 12:04 UTC, chrisburr requested changes, later dismissed
Needs to

* replace getTransfromationFiles with getTransfromationFilesAsJsonString
* deprecate getTransfromationFilesAsJsonString
* remove include_web_records flag

2024-11-06 10:41 UTC, chrisburr commented on src/DIRAC/TransformationSystem/DB/TransformationDB.py
> -            webList = [[str(item) if not isinstance(item, int) else item for item in row] for row in res["Value"]]
Can you remove this from the tasks as well

2024-11-06 10:43 UTC, chrisburr commented
Otherwise looks good

2024-11-06 12:06 UTC, chrisburr commented on src/DIRAC/TransformationSystem/DB/TransformationDB.py
> -        result["Records"] = webList
isn't `webList` now an unused variable?

2024-11-06 15:20 UTC, fstagni approved these changes

2024-11-06 15:20 UTC, merged